// Mock data for development until Supabase is connected

export const mockRestaurants = [
  {
    id: "1",
    name: "DP Restaurant",
    description: "Delicious local dishes with fast service. Known for the best jollof rice on campus!",
    image_url: "/restaurants/dp.jpg",
    banner_url: "/restaurants/dp-banner.jpg",
    location: "D Hall, Main Campus",
    rating: 4.5,
    total_orders: 1250,
    is_open: true,
    delivery_time: "20-30 min",
    delivery_fee: 200,
    categories: ["Rice", "Swallow", "Protein"],
  },
  {
    id: "2",
    name: "Manna Palace",
    description: "Best rice and stew on campus. Try our special fried rice!",
    image_url: "/restaurants/manna.jpg",
    banner_url: "/restaurants/manna-banner.jpg",
    location: "Near Main Gate",
    rating: 4.7,
    total_orders: 2100,
    is_open: true,
    delivery_time: "25-35 min",
    delivery_fee: 200,
    categories: ["Rice", "Pasta", "Drinks"],
  },
  {
    id: "3",
    name: "Foodmart",
    description: "Quick bites, snacks, and refreshments for busy students",
    image_url: "/restaurants/foodmart.jpg",
    banner_url: "/restaurants/foodmart-banner.jpg",
    location: "Student Center",
    rating: 4.2,
    total_orders: 980,
    is_open: true,
    delivery_time: "15-20 min",
    delivery_fee: 150,
    categories: ["Snacks", "Drinks", "Breakfast"],
  },
  {
    id: "4",
    name: "Luwa Cafe",
    description: "Premium coffee, pastries and light meals. Perfect spot for studying!",
    image_url: "/restaurants/luwa.jpg",
    banner_url: "/restaurants/luwa-banner.jpg",
    location: "Library Complex",
    rating: 4.8,
    total_orders: 1850,
    is_open: true,
    delivery_time: "15-25 min",
    delivery_fee: 200,
    categories: ["Breakfast", "Snacks", "Drinks"],
  },
  {
    id: "5",
    name: "SOOMTA Kitchen",
    description: "Authentic African cuisine with a modern twist. Home of the best soups!",
    image_url: "/restaurants/soomta.jpg",
    banner_url: "/restaurants/soomta-banner.jpg",
    location: "New Site, Block A",
    rating: 4.6,
    total_orders: 1420,
    is_open: true,
    delivery_time: "30-40 min",
    delivery_fee: 250,
    categories: ["Swallow", "Soup", "Protein"],
  },
  {
    id: "6",
    name: "EXQUISITE",
    description: "Upscale dining experience. Continental and local delicacies",
    image_url: "/restaurants/exquisite.jpg",
    banner_url: "/restaurants/exquisite-banner.jpg",
    location: "Faculty of Arts",
    rating: 4.9,
    total_orders: 2300,
    is_open: true,
    delivery_time: "35-45 min",
    delivery_fee: 300,
    categories: ["Rice", "Pasta", "Protein"],
  },
  {
    id: "7",
    name: "Narsh Place",
    description: "Your go-to spot for sharwarma, burgers and grills",
    image_url: "/restaurants/narsh.jpg",
    banner_url: "/restaurants/narsh-banner.jpg",
    location: "Main Gate Area",
    rating: 4.4,
    total_orders: 1670,
    is_open: true,
    delivery_time: "20-30 min",
    delivery_fee: 200,
    categories: ["Snacks", "Protein", "Drinks"],
  },
  {
    id: "8",
    name: "Choplyfe",
    description: "Fast, fresh and affordable meals. Student favorite!",
    image_url: "/restaurants/choplyfe.jpg",
    banner_url: "/restaurants/choplyfe-banner.jpg",
    location: "Hostel Junction",
    rating: 4.3,
    total_orders: 1950,
    is_open: true,
    delivery_time: "20-25 min",
    delivery_fee: 150,
    categories: ["Rice", "Swallow", "Snacks"],
  },
  {
    id: "9",
    name: "Yellow Bus",
    description: "Campus food truck serving hot meals on wheels. Always fresh!",
    image_url: "/restaurants/yellowbus.jpg",
    banner_url: "/restaurants/yellowbus-banner.jpg",
    location: "Roaming Campus (Check app for location)",
    rating: 4.5,
    total_orders: 1120,
    is_open: true,
    delivery_time: "25-30 min",
    delivery_fee: 200,
    categories: ["Rice", "Snacks", "Drinks"],
  },
]

export const mockMenuItems = {
  "1": [ // DP Restaurant
    {
      id: "m1",
      name: "Jollof Rice & Chicken",
      description: "Our signature jollof rice with grilled chicken",
      price: 1500,
      image_url: "/menu/jollof-chicken.jpg",
      category: "Rice",
      is_available: true,
    },
    {
      id: "m2",
      name: "Fried Rice",
      description: "Delicious fried rice with mixed vegetables",
      price: 1200,
      image_url: "/menu/fried-rice.jpg",
      category: "Rice",
      is_available: true,
    },
    {
      id: "m3",
      name: "Eba & Egusi Soup",
      description: "Fresh eba with rich egusi soup and assorted meat",
      price: 1000,
      image_url: "/menu/eba-egusi.jpg",
      category: "Swallow",
      is_available: true,
    },
    {
      id: "m4",
      name: "Grilled Fish",
      description: "Freshly grilled tilapia",
      price: 2000,
      image_url: "/menu/grilled-fish.jpg",
      category: "Protein",
      is_available: true,
    },
    {
      id: "m5",
      name: "Coca-Cola",
      description: "Chilled soft drink",
      price: 200,
      image_url: "/menu/coke.jpg",
      category: "Drinks",
      is_available: true,
    },
  ],
  "2": [ // Manna Palace
    {
      id: "m6",
      name: "Special Fried Rice",
      description: "Fried rice with shrimps and chicken",
      price: 1800,
      image_url: "/menu/special-fried-rice.jpg",
      category: "Rice",
      is_available: true,
    },
    {
      id: "m7",
      name: "Jollof Spaghetti",
      description: "Spicy jollof spaghetti",
      price: 1300,
      image_url: "/menu/jollof-spaghetti.jpg",
      category: "Pasta",
      is_available: true,
    },
    {
      id: "m8",
      name: "Chicken & Chips",
      description: "Fried chicken with crispy fries",
      price: 1600,
      image_url: "/menu/chicken-chips.jpg",
      category: "Protein",
      is_available: true,
    },
  ],
  "3": [ // Foodmart
    {
      id: "m9",
      name: "Meat Pie",
      description: "Fresh baked meat pie",
      price: 300,
      image_url: "/menu/meat-pie.jpg",
      category: "Snacks",
      is_available: true,
    },
    {
      id: "m10",
      name: "Sausage Roll",
      description: "Crispy sausage roll",
      price: 250,
      image_url: "/menu/sausage-roll.jpg",
      category: "Snacks",
      is_available: true,
    },
    {
      id: "m11",
      name: "Smoothie",
      description: "Mixed fruit smoothie",
      price: 500,
      image_url: "/menu/smoothie.jpg",
      category: "Drinks",
      is_available: true,
    },
  ],
}

export const mockCategories = [
  { id: "all", name: "All", icon: "🍽️" },
  { id: "rice", name: "Rice & Pasta", icon: "🍚" },
  { id: "swallow", name: "Swallow & Soup", icon: "🍲" },
  { id: "protein", name: "Protein", icon: "🍗" },
  { id: "snacks", name: "Snacks", icon: "🥐" },
  { id: "drinks", name: "Drinks", icon: "🥤" },
  { id: "breakfast", name: "Breakfast", icon: "🍳" },
]

// Mock user for testing
export const mockUser = {
  id: "user-123",
  email: "student@campus.edu",
  role: "customer",
  full_name: "Test Student",
}

// Mock orders for vendor dashboard
export const mockOrders = [
  {
    id: "order-1",
    order_number: "CE-001234",
    customer_name: "John Doe",
    items: [
      { name: "Jollof Rice & Chicken", quantity: 2, price: 1500 },
      { name: "Coca-Cola", quantity: 1, price: 200 },
    ],
    total: 3200,
    status: "pending",
    delivery_location: "Room 204, Hall A",
    created_at: new Date().toISOString(),
  },
  {
    id: "order-2",
    order_number: "CE-001235",
    customer_name: "Jane Smith",
    items: [
      { name: "Fried Rice", quantity: 1, price: 1200 },
    ],
    total: 1400,
    status: "preparing",
    delivery_location: "Faculty of Engineering",
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
]
